import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from typing import Dict, Any

# --- HELPER: Text Wrapping ---
def draw_wrapped_text(c, text, x, y, max_width, line_height=12):
    if not text: return y
    words = text.split()
    line = ""
    for word in words:
        if c.stringWidth(line + word, "Helvetica", 10) < max_width:
            line += word + " "
        else:
            c.drawString(x, y, line)
            y -= line_height
            line = word + " "
    c.drawString(x, y, line)
    return y - line_height

# --- HELPER: PDF Generation ---
def generate_pdf_report(plans, user_profile, user_intent, filename="My_Application_Strategy.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    y = height - 50 
    
    # ==============================
    # 1. HEADER
    # ==============================
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "🎓 Application Strategy Dossier")
    y -= 25
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y, "Generated by Agentic AI for German University Admissions")
    y -= 30

    # ==============================
    # 2. APPLICANT PROFILE BOX
    # ==============================
    # Increased height from 70 to 90 to fit the 3rd row
    box_height = 90
    c.setLineWidth(1)
    c.setFillColorRGB(0.95, 0.95, 0.95) # Light grey
    c.rect(45, y - box_height - 5, width-90, box_height, fill=1, stroke=1)
    c.setFillColorRGB(0, 0, 0) # Black text
    
    # Title
    c.setFont("Helvetica-Bold", 12)
    c.drawString(55, y-15, "👤 APPLICANT PROFILE")
    
    # --- EXTRACT DATA ---
    u_cit = "Unknown"
    if user_profile and user_profile.citizenship:
        u_cit = getattr(user_profile.citizenship, 'country_of_citizenship', 'Unknown')

    u_gpa = "N/A"
    u_gpa_german = "N/A"
    if user_profile and user_profile.academic_background and user_profile.academic_background.bachelor_gpa:
        u_gpa = getattr(user_profile.academic_background.bachelor_gpa, 'score', 'N/A')
        u_gpa_german = getattr(user_profile.academic_background.bachelor_gpa, 'score_german', 'N/A')

    u_major = "Unknown"
    u_credits = "N/A"
    u_ects = "N/A"
    if user_profile and user_profile.academic_background:
        u_major = getattr(user_profile.academic_background, 'bachelor_field_of_study', 'Unknown')
        u_credits = getattr(user_profile.academic_background, 'total_credits_earned', 'N/A')
        u_ects = getattr(user_profile.academic_background, 'total_converted_ects', 'N/A')
    
    
    # Extract desired program and field of interests from user profile
    desired_programs = []
    fields_of_interest = []
    
    if user_profile and user_profile.desired_program:
        desired_programs = getattr(user_profile.desired_program, 'program_name', [])
        fields_of_interest = getattr(user_profile.desired_program, 'fields_of_interest', [])
    
    # Also check academic_background for fields_of_interest (backup)
    if not fields_of_interest and user_profile and user_profile.academic_background:
        fields_of_interest = getattr(user_profile.academic_background, 'fields_of_interest', [])
    
    # Format for display
    target_programs = ", ".join(desired_programs) if desired_programs else "Not specified"
    target_interests = ", ".join(fields_of_interest[:5]) if fields_of_interest else "Not specified"
    
    # Combine for display (truncate if too long)
    if target_programs != "Not specified" and target_interests != "Not specified":
        target_display = f"{target_programs} | Interests: {target_interests}"
    elif target_programs != "Not specified":
        target_display = target_programs
    elif target_interests != "Not specified":
        target_display = f"Interests: {target_interests}"
    else:
        target_display = "Not specified"
    
    if len(target_display) > 80:
        target_display = target_display[:77] + "..."

    # --- ROW 1: Origin & GPA ---
    c.setFont("Helvetica", 10)
    c.drawString(55, y-35, f"Origin: {u_cit}")
    if u_gpa_german != "N/A":
        c.drawString(300, y-35, f"GPA: {u_gpa} (German: {u_gpa_german})")
    else:
        c.drawString(300, y-35, f"Bachelor GPA: {u_gpa}")

    # --- ROW 2: Background & Credits/ECTS ---
    if len(u_major) > 35: u_major = u_major[:35] + "..."
    c.drawString(55, y-55, f"B.Sc Major: {u_major}")
    
    c.setFont("Helvetica-Bold", 10) # Bold for emphasis
    if u_ects != "N/A":
        c.drawString(300, y-55, f"Credits: {u_credits} → ECTS: {u_ects}")
    else:
        c.drawString(300, y-55, f"Total Credits: {u_credits}")
    c.setFont("Helvetica", 10)

    # --- ROW 3: TARGET / INTEREST (NEW) ---
    c.setLineWidth(0.5)
    c.line(55, y-65, width-55, y-65) # Thin separator line
    
    c.setFont("Helvetica-Bold", 10)
    c.drawString(55, y-80, "🎯 Target / Interest:")
    c.setFont("Helvetica", 10)
    c.drawString(160, y-80, target_display)

    y -= (box_height + 40) # Move cursor past the box

    # ==============================
    # 3. PROGRAM STRATEGIES
    # ==============================
    for plan in plans:
        if y < 200: 
            c.showPage()
            y = height - 50
            
        # Header
        c.setFillColorRGB(0.9, 0.9, 0.9) 
        c.rect(45, y-5, width-90, 20, fill=1, stroke=0)
        c.setFillColorRGB(0, 0, 0) 
        
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, f"{plan['program_name']}")
        y -= 20
        
        # Meta
        c.setFont("Helvetica-Bold", 10)
        c.drawString(50, y, f"University: {plan['university']}")
        c.drawString(300, y, f"Tuition: €{plan['tuition']}/sem")
        y -= 15
        c.setFont("Helvetica", 9)
        c.drawString(50, y, f"Mode: {plan['application_mode']}  |  URL: {plan['official_url'][:50]}...")
        y -= 20
        
        # Content
        c.setFont("Helvetica-Bold", 11)
        c.drawString(50, y, "📖 Program Content")
        y -= 15
        c.setFont("Helvetica", 9)
        desc = plan.get('course_content', 'No description available.')
        y = draw_wrapped_text(c, desc, 50, y, width-100)
        y -= 15
        
        # Timeline
        c.setFont("Helvetica-Bold", 11)
        c.drawString(50, y, "⏳ Action Timeline")
        y -= 15
        c.setFont("Helvetica", 10)
        
        for event in plan['timeline']:
            date_display = event['date']
            if hasattr(event['date'], 'strftime'):
                date_display = event['date'].strftime('%Y-%m-%d')
            
            prefix = "•"
            if event['type'] == 'overdue': 
                c.setFillColorRGB(0.8, 0, 0) 
                prefix = "🔥 [LATE]"
            elif event['type'] == 'critical':
                c.setFillColorRGB(0.8, 0, 0) 
                prefix = "🚨"
            elif event['type'] == 'deadline':
                c.setFillColorRGB(0, 0, 0.8) 
                prefix = "🏁"
            else:
                c.setFillColorRGB(0, 0, 0)
                
            c.drawString(60, y, f"{prefix} {date_display}: {event['event']}")
            y -= 12
        
        c.setFillColorRGB(0, 0, 0) 
        y -= 15

        # Checklist
        if y < 100: 
            c.showPage()
            y = height - 50

        c.setFont("Helvetica-Bold", 11)
        c.drawString(50, y, "📝 Required Documents")
        y -= 15
        c.setFont("Helvetica", 10)
        
        for item in plan['checklist']:
            c.drawString(60, y, f"[ ] {item}")
            y -= 12
            
        y -= 30 
        c.setLineWidth(0.5)
        c.line(50, y, width-50, y)
        y -= 30

    c.save()

# --- MAIN NODE ---
def agent_6_report_node(state: Dict[str, Any]) -> Dict[str, Any]:
    print("\n" + "="*60)
    print("📦 AGENT 6: COMPREHENSIVE PDF GENERATOR")
    print("="*60)
    
    # Get data from Agent5 (timeline) and Agent4 (full program details)
    timeline_plans = state.get("final_application_plans", [])
    selected_programs = state.get("selected_programs_with_checklists", [])
    user_profile = state.get("user_profile")
    user_intent = state.get("user_intent", "")
    
    if not timeline_plans:
        print("❌ No timeline plans to report.")
        return {}
    
    if not selected_programs:
        print("❌ No selected programs data found.")
        return {}
    
    # Merge Agent5's timeline with Agent4's full program data
    # Match by program_name and university
    merged_plans = []
    for timeline_plan in timeline_plans:
        prog_name = timeline_plan.get("program_name")
        uni_name = timeline_plan.get("university")
        
        # Find matching program from Agent4's output
        matching_program = None
        for prog in selected_programs:
            if prog.get("program_name") == prog_name and prog.get("university_name") == uni_name:
                matching_program = prog
                break
        
        if matching_program:
            # Merge timeline with full program data
            checklist_data = matching_program.get("checklist_data", {})
            merged_plan = {
                "program_name": prog_name,
                "university": uni_name,
                "official_url": timeline_plan.get("official_url", ""),
                "timeline": timeline_plan.get("timeline", []),
                "checklist": timeline_plan.get("checklist", []),
                # Add missing data from Agent4
                "tuition": matching_program.get("tuition_fee_per_semester_eur", 0),
                "application_mode": checklist_data.get("application_mode", "Unknown"),
                "course_content": matching_program.get("course_content_summary", "No description available.")
            }
            merged_plans.append(merged_plan)
        else:
            print(f"⚠️  Warning: Could not find full data for {prog_name}")
            # Use timeline plan as-is with defaults
            merged_plan = {
                **timeline_plan,
                "tuition": 0,
                "application_mode": "Unknown",
                "course_content": "No description available."
            }
            merged_plans.append(merged_plan)
    
    filename = "My_Application_Strategy.pdf"
    
    # Generate PDF with merged data
    generate_pdf_report(merged_plans, user_profile, user_intent, filename)
    
    print(f"   ✅ Report generated: '{filename}'")
    print(f"      - Included user profile (GPA, credits, citizenship)")
    print(f"      - Included desired program and field of interests")
    print(f"      - Included full program details (tuition, mode, content)")
    print(f"      - Included timeline and checklist")
    
    return {"reports_generated": True}